services:
  # ───────── server_udp (réception + INSERT) ─────────
  server_udp:
    build: ./server_udp
    container_name: server_udp
    # host networking = pas de NAT UDP, plus simple pour le drone
    network_mode: host
    environment:
      PGURI: postgresql://user:password@localhost:5432/mydb
      UDP_PORT: 9000
      UDP_MTU: 1300
    volumes:
      - ./map-server/config:/opt/server_udp/config:ro

  # ───────── (facultatif) petit sink UDP de debug ────
  udp_sink:
    image: alpine
    network_mode: host
    command: >
      sh -c "apk add --no-cache socat &&
             echo '[sink] listening on 9000 …' &&
             socat -v udp-recv:9000 -"
