services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 30s
      retries: 5
  map-server:
    build: ./map-server
    depends_on: 
      db:
        condition: service_healthy
    ports: ["9000:9000"]
    environment:
      UDP_PORT: 9000
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      batch_size: 1000
      FLUSH_INTERVAL_MS: 3000

volumes:
  db_data: