services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  map-server:
    build: ./map-server
    depends_on: [db]
    ports: ["9000:9000"]
    environment:
      UDP_PORT: 9000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: ros_db
      batch_size: 100
      FLUSH_INTERVAL_MS: 3000

volumes:
  db_data: